//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGEP.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditoriaGlobalTB
    {
        public int IdAuditoria { get; set; }
        public int IdUsuario { get; set; }
        public string TablaAfectada { get; set; }
        public int IdRegistro { get; set; }
        public string Accion { get; set; }
        public string CampoAfectado { get; set; }
        public string DatosAnteriores { get; set; }
        public string DatosNuevos { get; set; }
    
        public virtual UsuariosTB UsuariosTB { get; set; }
    }
}
