//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGEP.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class BolsaEmpleoTB
    {
        public int IdEmpleo { get; set; }
        public string Empresa { get; set; }
        public string Descripcion { get; set; }
        public string Requisitos { get; set; }
        public System.DateTime FechaPublicacion { get; set; }
        public System.DateTime FechaLimite { get; set; }
        public int IdEstado { get; set; }
        public string AreaAfin { get; set; }
        public Nullable<int> IdDireccion { get; set; }
        public Nullable<int> IdModalidad { get; set; }
    
        public virtual DireccionesTB DireccionesTB { get; set; }
        public virtual EstadosTB EstadosTB { get; set; }
        public virtual ModalidadesTB ModalidadesTB { get; set; }
    }
}
