//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGEP.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComentariosPracticaTB
    {
        public int IdComentario { get; set; }
        public string Comentario { get; set; }
        public System.DateTime Fecha { get; set; }
        public int IdUsuario { get; set; }
        public int IdPractica { get; set; }
        public string Nota { get; set; }
        public string Tipo { get; set; }
    
        public virtual PracticaEstudianteTB PracticaEstudianteTB { get; set; }
        public virtual UsuariosTB UsuariosTB { get; set; }
    }
}
