//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGEP.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComunicadosTB
    {
        public int IdComunicado { get; set; }
        public string Nombre { get; set; }
        public string Informacion { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Poblacion { get; set; }
        public Nullable<System.DateTime> FechaLimite { get; set; }
        public int IdUsuario { get; set; }
        public int IdEstado { get; set; }
    
        public virtual EstadosTB EstadosTB { get; set; }
        public virtual UsuariosTB UsuariosTB { get; set; }
    }
}
