//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGEP.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentosTB
    {
        public int IdDocumento { get; set; }
        public string Documento { get; set; }
        public string Tipo { get; set; }
        public string RutaArchivo { get; set; }
        public System.DateTime FechaSubida { get; set; }
        public int IdUsuario { get; set; }
        public Nullable<int> IdComunicado { get; set; }
    
        public virtual ComunicadosTB ComunicadosTB { get; set; }
        public virtual UsuariosTB UsuariosTB { get; set; }
    }
}
