//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGEP.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpleosTB
    {
        public int IdEmpleo { get; set; }
        public string NombrePuesto { get; set; }
        public string Mensaje { get; set; }
        public int IdEstado { get; set; }
    
        public virtual EstadosTB EstadosTB { get; set; }
    }
}
