//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGEP.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class EspecialidadesVacantesTB
    {
        public int IdEspecialidadVacante { get; set; }
        public int IdEspecialidad { get; set; }
        public int IdVacante { get; set; }
    
        public virtual EspecialidadesTB EspecialidadesTB { get; set; }
        public virtual VacantesPracticasTB VacantesPracticasTB { get; set; }
    }
}
