//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGEP.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class EstudianteEncargadoTB
    {
        public int IdEstudianteEncargado { get; set; }
        public int IdEncargado { get; set; }
        public int IdUsuario { get; set; }
        public string Parentesco { get; set; }
        public int IdEstado { get; set; }
    
        public virtual EncargadosTB EncargadosTB { get; set; }
        public virtual EstadosTB EstadosTB { get; set; }
        public virtual UsuariosTB UsuariosTB { get; set; }
    }
}
