//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGEP.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class InformacionMedicaTB
    {
        public int IdInfoMedica { get; set; }
        public int IdUsuario { get; set; }
        public string Padecimiento { get; set; }
        public string Tratamiento { get; set; }
        public string Alergia { get; set; }
    
        public virtual UsuariosTB UsuariosTB { get; set; }
    }
}
