//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGEP.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SIGEPEntities : DbContext
    {
        public SIGEPEntities()
            : base("name=SIGEPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AuditoriaGlobalTB> AuditoriaGlobalTB { get; set; }
        public virtual DbSet<BolsaEmpleoTB> BolsaEmpleoTB { get; set; }
        public virtual DbSet<CantonesTB> CantonesTB { get; set; }
        public virtual DbSet<ComentariosPracticaTB> ComentariosPracticaTB { get; set; }
        public virtual DbSet<ComunicadosTB> ComunicadosTB { get; set; }
        public virtual DbSet<DireccionesTB> DireccionesTB { get; set; }
        public virtual DbSet<DistritosTB> DistritosTB { get; set; }
        public virtual DbSet<DocumentosTB> DocumentosTB { get; set; }
        public virtual DbSet<EmailsTB> EmailsTB { get; set; }
        public virtual DbSet<EmpleosTB> EmpleosTB { get; set; }
        public virtual DbSet<EmpresasTB> EmpresasTB { get; set; }
        public virtual DbSet<EncargadosTB> EncargadosTB { get; set; }
        public virtual DbSet<EspecialidadesTB> EspecialidadesTB { get; set; }
        public virtual DbSet<EspecialidadesVacantesTB> EspecialidadesVacantesTB { get; set; }
        public virtual DbSet<EstadosTB> EstadosTB { get; set; }
        public virtual DbSet<EstudianteEncargadoTB> EstudianteEncargadoTB { get; set; }
        public virtual DbSet<FormacionAcademicaTB> FormacionAcademicaTB { get; set; }
        public virtual DbSet<InformacionLaboralTB> InformacionLaboralTB { get; set; }
        public virtual DbSet<InformacionMedicaTB> InformacionMedicaTB { get; set; }
        public virtual DbSet<ModalidadesTB> ModalidadesTB { get; set; }
        public virtual DbSet<PracticaEstudianteTB> PracticaEstudianteTB { get; set; }
        public virtual DbSet<ProvinciasTB> ProvinciasTB { get; set; }
        public virtual DbSet<RolesTB> RolesTB { get; set; }
        public virtual DbSet<SeccionesTB> SeccionesTB { get; set; }
        public virtual DbSet<TelefonosTB> TelefonosTB { get; set; }
        public virtual DbSet<UsuarioEspecialidadTB> UsuarioEspecialidadTB { get; set; }
        public virtual DbSet<UsuariosTB> UsuariosTB { get; set; }
        public virtual DbSet<VacantesPracticasTB> VacantesPracticasTB { get; set; }
    
        public virtual ObjectResult<LoginSP_Result> LoginSP(string cEDULA, string cONTRASENNA)
        {
            var cEDULAParameter = cEDULA != null ?
                new ObjectParameter("CEDULA", cEDULA) :
                new ObjectParameter("CEDULA", typeof(string));
    
            var cONTRASENNAParameter = cONTRASENNA != null ?
                new ObjectParameter("CONTRASENNA", cONTRASENNA) :
                new ObjectParameter("CONTRASENNA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LoginSP_Result>("LoginSP", cEDULAParameter, cONTRASENNAParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> RegistroSP(string nombre, string apellido1, string apellido2, string correo, Nullable<int> idEspecialidad, Nullable<System.DateTime> fechaNacimiento, Nullable<int> idSeccion, string contrasenna, string cedula)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var apellido1Parameter = apellido1 != null ?
                new ObjectParameter("Apellido1", apellido1) :
                new ObjectParameter("Apellido1", typeof(string));
    
            var apellido2Parameter = apellido2 != null ?
                new ObjectParameter("Apellido2", apellido2) :
                new ObjectParameter("Apellido2", typeof(string));
    
            var correoParameter = correo != null ?
                new ObjectParameter("Correo", correo) :
                new ObjectParameter("Correo", typeof(string));
    
            var idEspecialidadParameter = idEspecialidad.HasValue ?
                new ObjectParameter("IdEspecialidad", idEspecialidad) :
                new ObjectParameter("IdEspecialidad", typeof(int));
    
            var fechaNacimientoParameter = fechaNacimiento.HasValue ?
                new ObjectParameter("FechaNacimiento", fechaNacimiento) :
                new ObjectParameter("FechaNacimiento", typeof(System.DateTime));
    
            var idSeccionParameter = idSeccion.HasValue ?
                new ObjectParameter("IdSeccion", idSeccion) :
                new ObjectParameter("IdSeccion", typeof(int));
    
            var contrasennaParameter = contrasenna != null ?
                new ObjectParameter("Contrasenna", contrasenna) :
                new ObjectParameter("Contrasenna", typeof(string));
    
            var cedulaParameter = cedula != null ?
                new ObjectParameter("Cedula", cedula) :
                new ObjectParameter("Cedula", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("RegistroSP", nombreParameter, apellido1Parameter, apellido2Parameter, correoParameter, idEspecialidadParameter, fechaNacimientoParameter, idSeccionParameter, contrasennaParameter, cedulaParameter);
        }
    }
}
