//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGEP.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SIGEPEntities : DbContext
    {
        public SIGEPEntities()
            : base("name=SIGEPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AuditoriaGlobalTB> AuditoriaGlobalTB { get; set; }
        public virtual DbSet<BolsaEmpleoTB> BolsaEmpleoTB { get; set; }
        public virtual DbSet<CantonesTB> CantonesTB { get; set; }
        public virtual DbSet<ComentariosPracticaTB> ComentariosPracticaTB { get; set; }
        public virtual DbSet<ComunicadosTB> ComunicadosTB { get; set; }
        public virtual DbSet<DireccionesTB> DireccionesTB { get; set; }
        public virtual DbSet<DistritosTB> DistritosTB { get; set; }
        public virtual DbSet<DocumentosTB> DocumentosTB { get; set; }
        public virtual DbSet<EmailsTB> EmailsTB { get; set; }
        public virtual DbSet<EmpleosTB> EmpleosTB { get; set; }
        public virtual DbSet<EmpresasTB> EmpresasTB { get; set; }
        public virtual DbSet<EncargadosTB> EncargadosTB { get; set; }
        public virtual DbSet<EspecialidadesTB> EspecialidadesTB { get; set; }
        public virtual DbSet<EspecialidadesVacantesTB> EspecialidadesVacantesTB { get; set; }
        public virtual DbSet<EstadosTB> EstadosTB { get; set; }
        public virtual DbSet<EstudianteEncargadoTB> EstudianteEncargadoTB { get; set; }
        public virtual DbSet<FormacionAcademicaTB> FormacionAcademicaTB { get; set; }
        public virtual DbSet<InformacionLaboralTB> InformacionLaboralTB { get; set; }
        public virtual DbSet<InformacionMedicaTB> InformacionMedicaTB { get; set; }
        public virtual DbSet<ModalidadesTB> ModalidadesTB { get; set; }
        public virtual DbSet<PracticaEstudianteTB> PracticaEstudianteTB { get; set; }
        public virtual DbSet<ProvinciasTB> ProvinciasTB { get; set; }
        public virtual DbSet<RolesTB> RolesTB { get; set; }
        public virtual DbSet<SeccionesTB> SeccionesTB { get; set; }
        public virtual DbSet<TelefonosTB> TelefonosTB { get; set; }
        public virtual DbSet<UsuarioEspecialidadTB> UsuarioEspecialidadTB { get; set; }
        public virtual DbSet<UsuariosTB> UsuariosTB { get; set; }
        public virtual DbSet<VacantesPracticasTB> VacantesPracticasTB { get; set; }
    }
}
