//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGEP.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotasEstudiantesTB
    {
        public int IdNota { get; set; }
        public int IdUsuario { get; set; }
        public Nullable<decimal> Nota1 { get; set; }
        public Nullable<decimal> Nota2 { get; set; }
        public Nullable<decimal> NotaFinal { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public Nullable<System.DateTime> FechaActualizacion { get; set; }
        public int IdProfesor { get; set; }
    
        public virtual UsuariosTB UsuariosTB { get; set; }
        public virtual UsuariosTB UsuariosTB1 { get; set; }
    }
}
