//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGEP.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotasEstudiantesTB
    {
        public int IdNota { get; set; }
        public int IdUsuario { get; set; }
        public Nullable<decimal> Nota1 { get; set; }
        public Nullable<decimal> Nota2 { get; set; }
        public Nullable<decimal> NotaFinal { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public Nullable<System.DateTime> FechaActualizacion { get; set; }
        public int IdProfesor { get; set; }
    
        public virtual UsuariosTB UsuariosTB { get; set; }
        public virtual UsuariosTB UsuariosTB1 { get; set; }
    }
}
