//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGEP.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PracticaEstudianteTB
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PracticaEstudianteTB()
        {
            this.ComentariosPracticaTB = new HashSet<ComentariosPracticaTB>();
        }
    
        public int IdPractica { get; set; }
        public int IdVacante { get; set; }
        public int IdUsuario { get; set; }
        public System.DateTime FechaAplicacion { get; set; }
        public int IdEstado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ComentariosPracticaTB> ComentariosPracticaTB { get; set; }
        public virtual EstadosTB EstadosTB { get; set; }
        public virtual UsuariosTB UsuariosTB { get; set; }
        public virtual VacantesPracticasTB VacantesPracticasTB { get; set; }
    }
}
