//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGEP.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class SeccionesTB
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SeccionesTB()
        {
            this.UsuariosTB = new HashSet<UsuariosTB>();
        }
    
        public int IdSeccion { get; set; }
        public string Seccion { get; set; }
        public int IdEstado { get; set; }
    
        public virtual EstadosTB EstadosTB { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsuariosTB> UsuariosTB { get; set; }
    }
}
