//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGEP.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TelefonosTB
    {
        public int IdTelefono { get; set; }
        public Nullable<int> IdUsuario { get; set; }
        public Nullable<int> IdEmpresa { get; set; }
        public Nullable<int> IdEncargado { get; set; }
        public string Telefono { get; set; }
    
        public virtual EmpresasTB EmpresasTB { get; set; }
        public virtual EncargadosTB EncargadosTB { get; set; }
        public virtual UsuariosTB UsuariosTB { get; set; }
    }
}
