//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGEP.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsuariosTB
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UsuariosTB()
        {
            this.AuditoriaGlobalTB = new HashSet<AuditoriaGlobalTB>();
            this.ComentariosPracticaTB = new HashSet<ComentariosPracticaTB>();
            this.ComunicadosTB = new HashSet<ComunicadosTB>();
            this.DocumentosTB = new HashSet<DocumentosTB>();
            this.EmailsTB = new HashSet<EmailsTB>();
            this.EstudianteEncargadoTB = new HashSet<EstudianteEncargadoTB>();
            this.FormacionAcademicaTB = new HashSet<FormacionAcademicaTB>();
            this.InformacionLaboralTB = new HashSet<InformacionLaboralTB>();
            this.InformacionMedicaTB = new HashSet<InformacionMedicaTB>();
            this.PracticaEstudianteTB = new HashSet<PracticaEstudianteTB>();
            this.TelefonosTB = new HashSet<TelefonosTB>();
            this.UsuarioEspecialidadTB = new HashSet<UsuarioEspecialidadTB>();
        }
    
        public int IdUsuario { get; set; }
        public string Cedula { get; set; }
        public string Nombre { get; set; }
        public string Apellido1 { get; set; }
        public string Apellido2 { get; set; }
        public string Contrasenna { get; set; }
        public System.DateTime FechaNacimiento { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public System.DateTime FechaEgreso { get; set; }
        public Nullable<int> IdSeccion { get; set; }
        public Nullable<int> IdDireccion { get; set; }
        public int IdRol { get; set; }
        public int IdEstado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AuditoriaGlobalTB> AuditoriaGlobalTB { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ComentariosPracticaTB> ComentariosPracticaTB { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ComunicadosTB> ComunicadosTB { get; set; }
        public virtual DireccionesTB DireccionesTB { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentosTB> DocumentosTB { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmailsTB> EmailsTB { get; set; }
        public virtual EstadosTB EstadosTB { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EstudianteEncargadoTB> EstudianteEncargadoTB { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FormacionAcademicaTB> FormacionAcademicaTB { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InformacionLaboralTB> InformacionLaboralTB { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InformacionMedicaTB> InformacionMedicaTB { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PracticaEstudianteTB> PracticaEstudianteTB { get; set; }
        public virtual RolesTB RolesTB { get; set; }
        public virtual SeccionesTB SeccionesTB { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TelefonosTB> TelefonosTB { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsuarioEspecialidadTB> UsuarioEspecialidadTB { get; set; }
    }
}
