//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGEP.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class VacantesPracticasTB
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VacantesPracticasTB()
        {
            this.EspecialidadesVacantesTB = new HashSet<EspecialidadesVacantesTB>();
            this.PracticaEstudianteTB = new HashSet<PracticaEstudianteTB>();
        }
    
        public int IdVacante { get; set; }
        public string Nombre { get; set; }
        public int IdEmpresa { get; set; }
        public string Requerimientos { get; set; }
        public Nullable<System.DateTime> FechaMaxAplicacion { get; set; }
        public Nullable<int> NumCupos { get; set; }
        public Nullable<System.DateTime> FechaCierre { get; set; }
        public string Descripcion { get; set; }
        public string Tipo { get; set; }
        public int IdEstado { get; set; }
        public Nullable<int> IdModalidad { get; set; }
        public string Ubicacion { get; set; }
    
        public virtual EmpresasTB EmpresasTB { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EspecialidadesVacantesTB> EspecialidadesVacantesTB { get; set; }
        public virtual EstadosTB EstadosTB { get; set; }
        public virtual ModalidadesTB ModalidadesTB { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PracticaEstudianteTB> PracticaEstudianteTB { get; set; }
    }
}
